os: linux
sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - gcc-7
     - g++-7
     - cmake


before_script:
 - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 

script:
 - mkdir build
 - cd build
 - cmake ..
 - make
 - ./TravisTest
